# -*- coding: utf-8 -*-
# :Project:   pg_query -- Travis CI configuration
# :Created:   lun 07 ago 2017 00:44:48 CEST
# :Author:    Lele Gaifax <lele@metapensiero.it>
# :License:   GNU General Public License version 3 or later
# :Copyright: © 2017 Lele Gaifax
#

language: python
python:
  - "3.6"
install: "pip install -r requirements-test.txt"
script: "py.test ./tests"
